name: npc
description: Near Procedure Call.
version: 0.0.1
homepage: https://github.com/neutronstarer/npc_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: <2.0.0
  cancelable: <1.0.0
dev_dependencies:
  test: