name: npc
description: Near Procedure Call.
version: 0.0.5
homepage: https://github.com/neutronstarer/npc_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"
  cancelable: ">=0.0.1 <1.0.0"
dev_dependencies:
  test: