name: npc
description: Near Procedure Call.
version: 2.0.0
homepage: https://github.com/neutronstarer/npc_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cancelable: ^1.0.2
dev_dependencies:
  test: ^1.0.0